export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const LOAD_CLASS_SUCCESS = 'LOAD_CLASS_SUCCESS';
export const LOAD_CLASS_FAIL = 'LOAD_CLASS_FAIL';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_ERROR = 'CREATE_CLASS_ERROR';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';
export const CLASSROOMS_ERROR = 'CLASSROOMS_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const POST_ERROR = 'POST_ERROR';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';
export const RESET_POSTS = 'RESET_POSTS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const CLASS_DETAIL_ERROR = 'CLASS_DETAIL_ERROR';
export const GET_CLASS_DETAIL = 'GET_CLASS_DETAIL';
export const GET_CLASS_DETAIL_SUCCESS = 'GET_CLASS_DETAIL_SUCCESS';
export const RESET_CLASS_DETAIL = 'RESET_CLASS_DETAIL';

export const GET_MEETINGS = 'GET_MEETINGS';
export const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
export const MEETING_ERROR = 'MEETING_ERROR';
export const ADD_MEETING_SUCCESS = 'ADD_MEETING_SUCCESS';
export const ADD_MEETING_ERROR = 'ADD_MEETING_ERROR';
export const RESET_MEETINGS = 'RESET_MEETINGS';
export const ADD_MEETING = 'ADD_MEETING';

export const GET_CLASS_NOTIFICATIONS = 'GET_CLASS_NOTIFICATIONS';
export const GET_CLASS_NOTIFICATIONS_SUCCESS =
  'GET_CLASS_NOTIFICATIONS_SUCCESS';
export const GET_CLASS_NOTIFICATIONS_ERROR = 'GET_CLASS_NOTIFICATIONS_ERROR';
export const RESET_CLASS_NOTIFICATIONS = 'RESET_CLASS_NOTIFICATIONS';
export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';

export const GET_CLASS_TOPICS = 'GET_CLASS_TOPICS';
export const GET_CLASS_TOPICS_SUCCESS = 'GET_CLASS_TOPICS_SUCCESS';
export const GET_CLASS_TOPICS_ERROR = 'GET_CLASS_TOPICS_ERROR';
export const RESET_CLASS_TOPICS = 'RESET_CLASS_TOPICS';
export const ADD_TOPIC_ERROR = 'ADD_TOPIC_ERROR';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
